---
title: "edgewise_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(ggplot2)
require(energy)
require(parallel)
require(tidyverse)
require(mltools)
ncores <- parallel::detectCores() - 1

```

```{r}
preproc <- readRDS('../data/dcorr/inputs_fMRI_AAL.rds')
```

```{r}
methods <- c("Raw", "conditional ComBat", "ComBat", "causal ComBat")

R <- 10000

cov.tab <- preproc.caus$covariates
datasets <- unique(cov.tab$Dataset)
# get subsets of data corresponding to the subset causal ComBat runs on
Xs <- lapply(methods, function(meth) {
  cov.tab.meth <- preproc[[meth]]$covariates
  idx.match <- (cov.tab.meth %>%
                  right_join(cov.tab %>% select(Subid, Session), by=c("Subid"="Subid", "Session"="Session")))$id
  preproc[[meth]]$graphs[idx.match,]
})
names(Xs) <- methods
d <- dim(Xs$Raw)[2]

pos2coord<-function(pos=NULL, coord=NULL, dim.mat=NULL){
 if(is.null(pos) & is.null(coord) | is.null(dim.mat)){
  stop("must supply either 'pos' or 'coord', and 'dim.mat'")
 }
 if(is.null(pos) & !is.null(coord) & !is.null(dim.mat)){
  pos <- ((coord[,2]-1)*dim.mat[1])+coord[,1] 
  return(pos)
 }
 if(!is.null(pos) & is.null(coord) & !is.null(dim.mat)){
  coord <- matrix(NA, nrow=length(pos), ncol=2)
  coord[,1] <- ((pos-1) %% dim.mat[1]) +1
  coord[,2] <- ((pos-1) %/% dim.mat[1]) +1
  return(coord)
 }
}
# AAL parcellation has 116 vertices
nv <- 116

Y = preproc.caus$covariates$Sex; Z.caus = preproc.caus$covariates$Age
DY <- dist(Y); DZ.caus <- dist(Z.caus)
res <- do.call(rbind, lapply(methods, function(meth) {
  if (meth == "Raw") {
    # if Raw, account for dataset in partial DCorr
    Z <- cbind(one_hot(data.table(Dataset=factor(preproc.caus$covariates$Dataset))), Age=Z.caus)
    Z.sc <- scale(Z)
    DZ <- dist(Z.sc)
  } else {
    DZ <- DZ.caus
  }
  X <- Xs[[meth]]
  # for each edge, pdcorr(edge, sex | age) or pdcorr(edge, sex | age, dataset)
  do.call(rbind, mclapply(1:d, function(i) {
    i.coord <- pos2coord(i, dim.mat=c(nv, nv))
    # check if coordinate in upper triangle
    if (i.coord[1] > i.coord[2]) {
      print(i)
      DX <- dist(X[,i])
      test <- pdcor.test(DX, DY, DZ, R=R)
      return(data.frame(Row=i.coord[1], Column=i.coord[2], Edge=i, Statistic=test$statistic,
                        # p-value computation from energy package doesn't make sense
                        p.value=(1 + sum(test$replicates >= test$statistic))/(1 + R)))
    } else {
      return(NULL)
    }
  }, mc.cores = ncores)) %>% mutate(Method=meth)
})) %>% mutate(Set="Causal Subset")

saveRDS(res, '../data/dcorr/outputs_edgewise_ss.rds')
```

```{r}
methods <- c("Raw", "conditional ComBat", "ComBat")

R <- 10000
datasets <- unique(cov.tab$Dataset)

pos2coord<-function(pos=NULL, coord=NULL, dim.mat=NULL){
 if(is.null(pos) & is.null(coord) | is.null(dim.mat)){
  stop("must supply either 'pos' or 'coord', and 'dim.mat'")
 }
 if(is.null(pos) & !is.null(coord) & !is.null(dim.mat)){
  pos <- ((coord[,2]-1)*dim.mat[1])+coord[,1] 
  return(pos)
 }
 if(!is.null(pos) & is.null(coord) & !is.null(dim.mat)){
  coord <- matrix(NA, nrow=length(pos), ncol=2)
  coord[,1] <- ((pos-1) %% dim.mat[1]) +1
  coord[,2] <- ((pos-1) %/% dim.mat[1]) +1
  return(coord)
 }
}
# AAL parcellation has 116 vertices
nv <- 116

res <- do.call(rbind, lapply(methods, function(meth) {
  X <- preproc[[meth]]$graphs
  cov.tab <- preproc[[meth]]$covariates
  Y <- cov.tab$Sex
  DY <- dist(Y)
  Z <- cov.tab$Age
  if (meth == "Raw") {
    # if Raw, account for dataset in partial DCorr
    Z <- cbind(one_hot(data.table(Dataset=factor(preproc.caus$covariates$Dataset))),
               Age=Z)
    Z.sc <- scale(Z)
    DZ <- dist(Z.sc)
  } else {
    DZ <- dist(Z)
  }
  d <- dim(X)[2]
  # for each edge, pdcorr(edge, sex | age) or pdcorr(edge, sex | age, dataset)
  do.call(rbind, mclapply(1:d, function(i) {
    i.coord <- pos2coord(i, dim.mat=c(nv, nv))
    # check if coordinate in upper triangle
    if (i.coord[1] > i.coord[2]) {
      print(i)
      DX <- dist(X[,i])
      test <- pdcor.test(DX, DY, DZ, R=R)
      return(data.frame(Row=i.coord[1], Column=i.coord[2], Edge=i, Statistic=test$statistic,
                        # p-value computation from energy package doesn't make sense
                        p.value=(1 + sum(test$replicates >= test$statistic))/(1 + R)))
    } else {
      return(NULL)
    }
  }, mc.cores = ncores)) %>% mutate(Method=meth)
})) %>% mutate(Set="All")

saveRDS(res, '../data/dcorr/outputs_edgewise_all.rds')
```

```{r}
meth.ord <- c("Raw", "ComBat", "conditional ComBat", "causal ComBat")
row.ord <- c("All", "Causal Subset")
outputs <- readRDS('../data/dcorr/outputs_edgewise_ss.rds') %>%
  # rbind(readRDS('../data/dcorr/outputs_edgewise_all.rds')) %>%
  mutate(Method=factor(Method, levels=meth.ord, ordered = TRUE),
         Set=factor(Set, levels=row.ord, ordered=TRUE)) %>%
  ungroup() %>%
  mutate(p.value=p.adjust(p.value, method="BH")) %>%
  group_by(Method) %>%
  arrange(p.value, desc(Statistic)) %>%
  mutate(Rank=row_number())
```

```{r}
dice <- function(a, b) {
  length(intersect(a, b))/length(union(a, b))
}

overlap_dice <- function(X) {
  methods = unique(X$Method)
  Dice=sapply(unique(X$Method), function(meth1) {
    sapply(unique(X$Method), function(meth2) {
      suppressMessages(
        dice((X %>% filter(Method == meth1) %>% ungroup())$Edge, 
             (X %>% filter(Method == meth2) %>% ungroup())$Edge))
    })
  })
  colnames(Dice) <- rownames(Dice) <- unique(X$Method)
  data.frame(Method1=colnames(Dice)[col(Dice)], Method2=rownames(Dice)[row(Dice)],
             DICE=c(Dice)) %>%
    mutate(Method1=factor(Method1, levels=meth.ord, ordered=TRUE),
           Method2=factor(Method2, levels=meth.ord, ordered=TRUE)) %>%
    arrange(Method1, Method2)
}

dice.mtx.lng <- outputs %>%
  filter(Rank <= 10) %>%
  overlap_dice()

dice.mtx.lng %>%
  filter(Method1 != Method2) %>%
  ggplot(aes(x=Method1, y=Method2, fill=DICE)) +
    geom_tile() +
    scale_fill_gradient(low="red", high="darkgreen") +
    xlab("Method") +
    ylab("Method") +
    ggtitle("DICE Overlap of Top 100 Edges PDcor(Edge, Sex | Age)") +
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
```

```{r, fig.width=10, fig.height=3}
alpha <- .05

plt <- outputs %>%
  rbind(outputs %>%
          mutate(Row.Tmp=Row, Row = Column, Column=Row.Tmp)) %>%
  filter(p.value <= alpha) %>%
  ggplot(aes(x=Row, y=Column, fill=Rank)) +
  geom_tile() +
  scale_fill_gradient(name="Rank", low="#530481", high="#fdf2fe") +
  ggtitle("Comparison of Significant Edges based on Correction Technique") +
  scale_x_discrete(breaks=c(1, 116), name="Parcel") +
  scale_y_discrete(breaks=c(1, 116), name="Parcel") +
  facet_grid(".~Method") +
  theme_bw()

plt <- ggplotGrob(plt)

plot(plt)
```